name: house_with_dogs
description: House With Dogs
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.0
